### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '-trim5'

### ISSUE THREAD

**Issue by brianpenghe** [brianpenghe/fastq-scripts#2]
Traceback (most recent call last):
  File "/woldlab/castor/home/georgi/code/trimfastq.py", line 246, in <module>
    run()
  File "/woldlab/castor/home/georgi/code/trimfastq.py", line 34, in run
    trim = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '-trim5'

**Comment by brianpenghe** [comment]
This error can be generated by specifying -trim5 without telling the script how many basepairs you need to keep, although it could be implied.
The solution is : always specify the int for the number of bp you want to keep even if you are just planning to trim from the 5' end
